pipeline {
    agent any

    stages {

        stage('Clonar código') {
            steps {
                checkout scm
            }
        }

        stage('Compilar proyecto') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Ejecutar pruebas') {
            steps {
                bat 'mvn test'
            }
        }

    }
}