pipeline {
    agent any

    stages {

        stage('Compilar proyecto') {
            steps {
                dir('mesadepartes') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Ejecutar pruebas') {
            steps {
                dir('mesadepartes') {
                    bat 'mvn test'
                }
            }
        }

    }
}
